import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Input } from '@/components/ui/input'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col w-full items-center min-h-screen">
          <div className="container">
            <SearchBar />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}

function SearchBar() {
  return (
    <div className="flex justify-center px-4 pt-10">
      <Input placeholder="Search products" className="w-3/4 h-12" />
    </div>
  )
}
